spring:
  application:
    name: Sagar POS System

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://pos-mysql:3306/pos_system}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false

server:
  port: 5000

jwt:
  secret: your-super-secret-key-your-super-secret-key
  expiration: 86400000