spring:
  application:
    name: Sagar POS System

  datasource:
    url: jdbc:h2:mem:posdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5000

jwt:
  secret: your-super-secret-key-your-super-secret-key
  expiration: 86400000